import io
f=io.open('src/js/features/lost-found.v1.js', 'rb')
data=f.read()
f.close()
data=data.replace(b"showSection('proxy-pickup')", b"showSection('pickup')")
data=data.replace(b"document.getElementById('proxy-pickup')", b"document.getElementById('pickup')")
data=data.replace(b"document.querySelectorAll('#proxy-pickup", b"document.querySelectorAll('#pickup")
data=data.replace(b"params.get('section') === 'proxy-pickup'", b"params.get('section') === 'pickup'")
f=io.open('src/js/features/lost-found.v1.js', 'wb')
f.write(data)
f.close()
